joint_robot_tp_node:
  ros__parameters:
    # speed command gain for the two robots
    kuka_gain: 0.05
    ur10_gain: 0.5
    # cartella output file txt dati
    exp_dir_name: "test1" 

    jl_gain_ref_rat: 0.2      # jl refer rate gain
    jl_act_delta: 0.3         # jl activation region

    eer_lin_gain: 1.0         # cartesian error gains
    eer_ori_gain: 1.0

    obv_dist_limit: 0.05      # basic obstacle av activation fcn
    obv_delta: 0.2            # params 

    obv_set_gain: 0.2         # set based obstacle avoidance reference
    obv_set_min_dist: 0.15    # rate(3) and activation(2) param
    obv_set_delta: 0.1
    obv_set_dist_limit: 0.05
    obv_set_act_delta: 0.2